# Refer to https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml for a working example
site_name: Ethereum Smart Contract Best Practices
site_url: https://github.com/ConsenSys/smart-contract-best-practices
site_description:
site_author: ConsenSys
repo_url: https://github.com/ConsenSys/smart-contract-best-practices

pages:
  - Home: index.md
  - General Philosophy: general_philosophy.md
  - Recommendations for Smart Contract Security in Solidity: recommendations.md
  - Known Attacks: known_attacks.md
  - Software Engineering Techniques: software_engineering.md
  - Token specific recommendations: tokens.md
  - Documentation and Procedures: documentation_procedures.md
  - Security Tools: security_tools.md
  - Security Notifications: security_notifications.md
  - Future improvements: future_improvements.md
  - Smart Contract Security Bibliography: bibliography.md
  - About:
    - Reviewers: about/reviewers.md
    - License: about/license.md
    - Contributing: about/contributing.md

theme:
  name: 'material'
  custom_dir: 'theme'
extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
